### ISSUE TITLE
IntegrityError: duplicate key value violates unique constraint "silk_response_request_id_key"

### ISSUE THREAD

**Issue by synotna** [django-silk/silk#26]
After activating silk certain urls began erring with:

IntegrityError: duplicate key value violates unique constraint "silk_response_request_id_key"
DETAIL:  Key (request_id)=(1166) already exists.

Sentry stack trace: http://toolbox1.tedc.de:9000/bidev/esldj/group/131/

**Comment by miguelfg** [comment]
Hi,

Same problem here :-( 
Here the trace in case it helps:

Traceback (most recent call last):

  File "/home/project_name/.virtualenvs/project_name/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 199, in get_response
    response = middleware_method(request, response)

  File "/home/project_name/.virtualenvs/project_name/local/lib/python2.7/site-packages/silk/middleware.py", line 105, in process_response
    self._process_response(response)

  File "/home/project_name/.virtualenvs/project_name/local/lib/python2.7/site-packages/silk/middleware.py", line 94, in _process_response
    silk_response = ResponseModelFactory(response).construct_response_model()

  File "/home/project_name/.virtualenvs/project_name/local/lib/python2.7/site-packages/silk/model_factory.py", line 246, in construct_response_model
    body=b)

  File "/home/project_name/.virtualenvs/project_name/local/lib/python2.7/site-packages/django/db/models/manager.py", line 157, in create
    return self.get_queryset().create(**kwargs)

  File "/home/project_name/.virtualenvs/project_name/local/lib/python2.7/site-packages/django/db/models/query.py", line 322, in create
    obj.save(force_insert=True, using=self.db)

  File "/home/project_name/.virtualenvs/project_name/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)

  File "/home/project_name/.virtualenvs/project_name/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)

  File "/home/project_name/.virtualenvs/project_name/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)

  File "/home/project_name/.virtualenvs/project_name/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)

  File "/home/project_name/.virtualenvs/project_name/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)

  File "/home/project_name/.virtualenvs/project_name/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)

  File "/home/project_name/.virtualenvs/project_name/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)

  File "/home/project_name/.virtualenvs/project_name/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)

  File "/home/project_name/.virtualenvs/project_name/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)

  File "/home/project_name/.virtualenvs/project_name/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)

IntegrityError: duplicate key value violates unique constraint "silk_response_request_id_key"
DETAIL:  Key (request_id)=(7) already exists.

====================
> pip freeze | grep silk
django-silk==0.4

====================

And we are using nginx with supervisor.

The current solution is catching the exception error and forget about it?

**Comment by mtford90** [comment]
@miguelfg Yeah for now catch that exception and ignore it.

I'm gonna nail this bug for good this weekend! Have been meaning to for ages.

**Comment by miguelfg** [comment]
@mtford90 I've wrap it in a try/except clause and it's working to me on the server.

Here is my custom_silk_middleware.py:

===========
import json
from django.utils import timezone

from silk.collector import DataCollector
from silk.profiling.profiler import silk_meta_profiler
from silk import models
from silk.middleware import SilkyMiddleware
from silk.model_factory import ResponseModelFactory, Logger


class CustomResponseModelFactory(ResponseModelFactory):

    def construct_response_model(self):
        assert self.request, 'Cant construct a response model if there is no request model'
        Logger.debug('Creating response model for request model with pk %s' % self.request.pk)
        b, content = self.body()
        raw_headers = self.response._headers
        headers = {}
        for k, v in raw_headers.items():
            try:
                header, val = v
            except ValueError:
                header, val = k, v
            finally:
                headers[header] = val
        try:
            silky_response = models.Response.objects.create(request=self.request,
                                                            status_code=self.response.status_code,
                                                            encoded_headers=json.dumps(headers),
                                                            body=b)
        except Exception as e:
            Logger.error('Silk error: {}'.format(e.message))
        # Text fields are encoded as UTF-8 in Django and hence will try to coerce
        # anything to we pass to UTF-8. Some stuff like binary will fail.
        try:
            silky_response.raw_body = content
        except UnicodeDecodeError:
            Logger.debug('NYI: Saving of binary response body')  # TODO
        return silky_response


class CustomSilkyMiddleware(SilkyMiddleware):

    def _process_response(self, response):
        with silk_meta_profiler():
            collector = DataCollector()
            collector.stop_python_profiler()
            silk_request = collector.request
            if silk_request:
                silk_response = CustomResponseModelFactory(response).construct_response_model()
                silk_response.save()
                silk_request.end_time = timezone.now()
                collector.finalise()
                silk_request.save()
            else:
                Logger.error('No request model was available when processing response. Did something go wrong in process_request/process_view?')
============

And my MIDDLEWARE var in settings has this now:
...
('middleware.custom_silk_profiling.CustomSilkyMiddleware',)
...

**Comment by miguelfg** [comment]
I added as a gist, it looks better -> https://gist.github.com/miguelfg/ec23abf454babc5e6e81

**Comment by mtford90** [comment]
@miguelfg Great. I'll everyone know this is fixed via this issue once complete

**Comment by mtford90** [comment]
I am hoping that is fixed now. Requests & Responses now have guids as the primary key, generated python side which should hopefully fix the conflicts

**Comment by karabijavad** [comment]
still getting this error:
```
Traceback (most recent call last):
  File "/home/javad/.pyenv/versions/django-rentapplication/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 204, in get_response
    response = middleware_method(request, response)
  File "/home/javad/.pyenv/versions/django-rentapplication/src/django-silk/silk/middleware.py", line 116, in process_response
    self._process_response(response)
  File "/home/javad/.pyenv/versions/django-rentapplication/src/django-silk/silk/middleware.py", line 104, in _process_response
    silk_response = ResponseModelFactory(response).construct_response_model()
  File "/home/javad/.pyenv/versions/django-rentapplication/src/django-silk/silk/model_factory.py", line 246, in construct_response_model
    body=b)
  File "/home/javad/.pyenv/versions/django-rentapplication/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/javad/.pyenv/versions/django-rentapplication/local/lib/python2.7/site-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/javad/.pyenv/versions/django-rentapplication/local/lib/python2.7/site-packages/django/db/models/base.py", line 590, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/javad/.pyenv/versions/django-rentapplication/local/lib/python2.7/site-packages/django/db/models/base.py", line 618, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/javad/.pyenv/versions/django-rentapplication/local/lib/python2.7/site-packages/django/db/models/base.py", line 699, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/javad/.pyenv/versions/django-rentapplication/local/lib/python2.7/site-packages/django/db/models/base.py", line 732, in _do_insert
    using=using, raw=raw)
  File "/home/javad/.pyenv/versions/django-rentapplication/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/javad/.pyenv/versions/django-rentapplication/local/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/javad/.pyenv/versions/django-rentapplication/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "/home/javad/.pyenv/versions/django-rentapplication/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/javad/.pyenv/versions/django-rentapplication/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/javad/.pyenv/versions/django-rentapplication/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "silk_response_request_id_key"
DETAIL:  Key (request_id)=(16e97114-e211-11e4-a8f3-e8b1fca5bb85) already exists.
```

**Comment by mtford90** [comment]
Damn it!

**Comment by mtford90** [comment]
Ok, I will need to rethink the way that this is done - @karabijavad what django version are you using? Also what server? Is it threaded or async?

**Comment by karabijavad** [comment]
1.7, and whatever manage.py test uses

**Comment by mtford90** [comment]
Oh it's happening during test runs... I hadn't thought about that, I wonder if there is something special about the way in which mock requests are setup that cause duplicates. Still doesn't make sense though I don't understand how a duplicate GUID can be created... :D

**Comment by karabijavad** [comment]
actually, i might have been using an older version... though i was pretty confident i had checked the silk version number before commenting just now.

seems to be fine at this moment... if it pops up again i will let you know

thanks for silk!

**Comment by mtford90** [comment]
@karabijavad I think you're on a version where this was supposed to be fixed though - as it looks like the requests are identifed by guids rather than the auto integers... So looks like this is prob still an issue. 

But yeah let me know if it keeps popping up, I will also try and replicate it myself at some stage - I hadn't thought about Silk being used in django test cases

**Comment by karabijavad** [comment]
good point, ok, ill see what i can do about replicating the problem.
fwiw:

```
MIDDLEWARE_CLASSES = [
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'silk.middleware.SilkyMiddleware',
    # 'axes.middleware.FailedLoginMiddleware',
    # 'rentapplication.middleware.PasswordExpirationMiddleware',
]
```

**Comment by mtford90** [comment]
cheers!

**Comment by riklaunim** [comment]
On 0.5.2 that errors do show up for me. If the     'silk.middleware.SilkyMiddleware' is at the top it's quite easy to get it. If last - can't get it, but some tests fail with that exception.

Some even throw "TypeError: 'model' is an invalid keyword argument for this function"

	self.client.post(url, data=data)
      File "/env/lib/python3.4/site-packages/django/test/client.py", line 482, in post
	secure=secure, **extra)
      File "/env/lib/python3.4/site-packages/django/test/client.py", line 296, in post
	secure=secure, **extra)
      File "/env/lib/python3.4/site-packages/django/test/client.py", line 358, in generic
	return self.request(**r)
      File "/env/lib/python3.4/site-packages/django/test/client.py", line 440, in request
	six.reraise(*exc_info)
      File "/env/lib/python3.4/site-packages/django/utils/six.py", line 550, in reraise
	raise value
      File "/env/lib/python3.4/site-packages/django/core/handlers/base.py", line 204, in get_response
	response = middleware_method(request, response)
      File "/env/lib/python3.4/site-packages/silk/middleware.py", line 116, in process_response
	self._process_response(response)
      File "/env/lib/python3.4/site-packages/silk/middleware.py", line 107, in _process_response
	collector.finalise()
      File "/env/lib/python3.4/site-packages/silk/collector.py", line 147, in finalise
	query_model = models.SQLQuery.objects.create(**query)
      File "/env/lib/python3.4/site-packages/django/db/models/manager.py", line 92, in manager_method
	return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/env/lib/python3.4/site-packages/django/db/models/query.py", line 370, in create
	obj = self.model(**kwargs)
      File "/env/lib/python3.4/site-packages/django/db/models/base.py", line 454, in __init__
	raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
    TypeError: 'model' is an invalid keyword argument for this function

**Comment by lucas03** [comment]
Hi,
any news? I am getting same error when someone (bots) are trying to access url that does not exists.
```
duplicate key value violates unique constraint "silk_response_request_id_key"
DETAIL:  Key (request_id)=(d099a20c-a122-11e5-a47a-0e7ea0966ed9) already exists.
```

**Comment by mcspud** [comment]
I too am having the same issue, but it only seems to appear when running Django (1.9.1) under Werkzeug or Gunicorn.  It seems to reinforce the idea that its a threading issue from above, as the Django dev server runs on a single thread.

**Comment by Eijebong** [comment]
Got the same issue with django 1.9 and uwsgi

**Comment by jvlomax** [comment]
Can confirm, have the same issue with django 1.9, running on a heroku server

**Comment by vshulyak** [comment]
We ran into the same issue.

**Comment by mtford90** [comment]
Gonna have another crack at this at the weekend.

**Comment by Alex3917** [comment]
I just got the same issue with apache and mod_wsgi.

**Comment by avelis** [comment]
@Alex3917  @vshulyak @jvlomax @Eijebong @mcspud @lucas03 

This thread has been long standing. I am going to do my best and try to find resolution. I have made a contribution that could get to the heart of the issue: 8073c0b231ca36bb820f6287cc44488417890f43

I am asking anyone on this thread to try the latest in master and see if it does resolve the issue you are experiencing.

Best.

**Comment by nikicat** [comment]
@avelis We've tried it: it doesn't prevent the error and contains a small bug with `e.message` https://app.getsentry.com/share/issue/36303837382e313134323035353639/

**Comment by avelis** [comment]
@nikicat Thanks. This is what I was looking for. I appreciate the help in trying this out. Going to do some investigation into the error you linked.

**Comment by avelis** [comment]
@nikicat I have decided to move the `transaction.atomic` as decorator to the method itself. If any integrity error occurs it should rollback. This also increases the readability of the `_process_response` method.

If you don't mind giving it a whirl, let me know what it does for you.

**Comment by digitaldavenyc** [comment]
Is this any closer to being resolved, still an issue for me on the latest with Django 1.9

**Comment by avelis** [comment]
@digitaldavenyc Unfortunately, I have been having trouble reproducing locally. If you can help me understand your setup to help reproduce consistently I can try and create a test rig for this scenario and try to solve it.

**Comment by digitaldavenyc** [comment]
Docker 1.9.1
Django 1.9
Python 3.5.1
Postgres (latest)
Gunicorn

Django settings:
SILKY_PYTHON_PROFILER = True

Using @silk_profile decorator on request functions

Is there any other information that would be helpful?

**Comment by avelis** [comment]
@digitaldavenyc How many Gunicorn processes are running (assuming within the container)? During the request response lifecycle is there any ajax calls being made to the same request url. Is it their first time making that call? Have they made that call before?

**Comment by reidransom** [comment]
For what it's worth, this issue only showed up for me after deploying to production a couple months ago...

Django 1.8
Python 2.6.7
Postgres (latest)
Gunicorn (3 processes)
Ubuntu 14.04 (no docker)
django-silk==0.5.6

**Comment by digitaldavenyc** [comment]
It's almost certain the call has been made before, there is a chain of 15 or so requests that are made and we cache some but we are using the silk profiler to track our performance gains using cache and when not using cache.

**Comment by jvlomax** [comment]
We have been having this issue too, but no Gunicorn or docker. We use:
Heroku
Django 1.9
Python 3.4
Silk(latest)
Postgres(latest)

Looks like Postgres is the one thing everyone shares?

**Comment by avelis** [comment]
@jvlomax if it is indeed Postgres then is less about a race condition and more to do about the key generation to insert into the table. hmmm, I know @mtford90 made earlier fixes to address that issue though...

**Comment by avelis** [comment]
@jvlomax @digitaldavenyc @reidransom Looking at the `Request` & `Response` model. I see the id charfield is using [uuid1](https://docs.python.org/2/library/uuid.html). If I created a fork and used uuid4 (with a migration). Would any of you try it out?

It is very possible that uuid1 is not the appropriate charfield generator in a production setting. However, I am not sure if this is indeed the issue.

Looking at the docstring is what lead me to believe that it could be the culprit:
```
def uuid1(node=None, clock_seq=None):
    """Generate a UUID from a host ID, sequence number, and the current time.
    If 'node' is not given, getnode() is used to obtain the hardware
    address.  If 'clock_seq' is given, it is used as the sequence number;
    otherwise a random 14-bit sequence number is chosen."""
```

**Comment by jvlomax** [comment]
I'd be happy to try it. I have tried something similar in my own fork, but was not successful.But i'm not very familiar with the code base so I may have misses something

**Comment by digitaldavenyc** [comment]
Yes absolutely

**Comment by reidransom** [comment]
I'll try it.  I'm on python 3.5.1 now.

**Comment by avelis** [comment]
@reidransom @jvlomax @digitaldavenyc I have published a branch called [uuid4](https://github.com/django-silk/silk/tree/uuid4). It has a migration to use the uuid4 method as the default value generator For the Request and Response model.

I attempted creating a South migration but it did not recognize a change.I believe this is the expected behavior.

Version libraries for reference.
`Django==1.8.9`
`South==1.0.2`

**Comment by digitaldavenyc** [comment]
Yeah that did not fix the issue... I still get an IntegrityError on the request_id. It's highly unlikely there is a UUID conflict when creating database entries, UUID is designed to prevent that.

**Comment by avelis** [comment]
@digitaldavenyc Could you provide a stacktrace on the IntegrityError?

**Comment by digitaldavenyc** [comment]
```
Internal Server Error: /silk
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "silk_response_request_id_key"
DETAIL:  Key (request_id)=(c6f1d94e-f13c-11e5-bdf2-0242ac110008) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python3.5/site-packages/silk/middleware.py", line 123, in process_response
    self._process_response(response)
  File "/usr/local/lib/python3.5/site-packages/silk/middleware.py", line 106, in _process_response
    silk_response = ResponseModelFactory(response).construct_response_model()
  File "/usr/local/lib/python3.5/site-packages/silk/model_factory.py", line 257, in construct_response_model
    body=b)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 401, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 728, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 812, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 851, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "silk_response_request_id_key"
DETAIL:  Key (request_id)=(c6f1d94e-f13c-11e5-bdf2-0242ac110008) already exists.
```

**Comment by avelis** [comment]
@digitaldavenyc I have added two more commits to the uuid4 branch for now.

Investigating further and it appears that the Request model is somehow trying to get saved a second time during the middleware lifecycle. I am not sure how though. In an effort to try and reduce that I have added some extra checks and referenced the id of the request object directly when creating the response object. This should reduce the chances of saving the parent object a second time.

**Comment by reidransom** [comment]
Just tried the latest and it didn't work for me:

```
ERROR 2016-03-24 09:09:54,654 base 6904 140436625557312 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/webapps/green/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "silk_response_request_id_key"
DETAIL:  Key (request_id)=(f32ea612-8ee8-4914-8580-99884839b5b8) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/webapps/green/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 223, in get_response
    response = middleware_method(request, response)
  File "/webapps/green/venv/lib/python3.5/site-packages/silk/middleware.py", line 126, in process_response
    self._process_response(request, response)
  File "/home/ubuntu/.pyenv/versions/3.5.1/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/webapps/green/venv/lib/python3.5/site-packages/silk/middleware.py", line 109, in _process_response
    silk_response = ResponseModelFactory(response).construct_response_model()
  File "/webapps/green/venv/lib/python3.5/site-packages/silk/model_factory.py", line 239, in construct_response_model
    body=b)
  File "/webapps/green/venv/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/webapps/green/venv/lib/python3.5/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/webapps/green/venv/lib/python3.5/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/webapps/green/venv/lib/python3.5/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/webapps/green/venv/lib/python3.5/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/webapps/green/venv/lib/python3.5/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/webapps/green/venv/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/webapps/green/venv/lib/python3.5/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/webapps/green/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/webapps/green/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/webapps/green/venv/lib/python3.5/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/webapps/green/venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/webapps/green/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "silk_response_request_id_key"
DETAIL:  Key (request_id)=(f32ea612-8ee8-4914-8580-99884839b5b8) already exists.
```

**Comment by digitaldavenyc** [comment]
I think this may have fixed it, I had to delete my docker container for postgres and reinstalled it. Initially the error was still there but after working with fresh data I don't seem to be getting it anymore. Perhaps anyone else still receiving this error should drop the table for django-silk and remigrate it?

**Comment by avelis** [comment]
@digitaldavenyc glad to see the branch resolved your issue. If I can get a second confirm by @reidransom or anyone else then I'd be happy to merge this branch into master.

@digitaldavenyc I think you are right about it not being a uuid1 v uuid4 issue but to really put this to rest I will probably leave it in.

From there I can look into asking @mtford90 for an official PyPi release.

*fingers crossed*

**Comment by digitaldavenyc** [comment]
UUID4 is a bit safer since it's based on randomness, UUID1 is based on the internal system clock and if you are writing fast enough there could be a collision but it would still be highly unlikely. I think [a53604d]( https://github.com/django-silk/silk/commit/a53604dc754f735b9f12b7deac66e395f0d7535b) and [f7cc486](https://github.com/django-silk/silk/commit/f7cc48606afd0a406966be4ff5ae0c90544999eb) are what fixed the issue.

**Comment by reidransom** [comment]
@avelis @digitaldavenyc  I tried f7cc486 again and didn't see any errors for about an hour.  I didn't drop/migrate the db table.  Then moved to 9c6c8dd and that was fine until 10 minutes ago... I got 2 errors for `/CHANGELOG.txt` and `/readme.html` which (like `/favicon.ico` from earlier) should return 404.  This error hasn't occurred for me on any pages that actually exist.

I'll try refreshing the db.

**Comment by digitaldavenyc** [comment]
How are errors on CHANGELOG.txt and readme.html related to this IntegrityError?

**Comment by reidransom** [comment]
Those endpoints don't exist in my urlconf.  They should return 404, but with silk middleware installed they produce 500 IntegrityError.

**Comment by avelis** [comment]
@digitaldavenyc @reidransom 9c6c8dd was recently made when I realized I was checking the presence of the `request` attribute on the `Request` model. In hindsight that made no sense. I could always go back one commit on the branch, however I am not sure when it could produce `True` to skip the if check.

**Comment by avelis** [comment]
@digitaldavenyc & @reidransom In the effort of keeping momentum going on this, I have merged the `uuid4` branch into `master`.

I believe the changes made can start to reduce the amount of errors that users are witnessing.

**Comment by reidransom** [comment]
Unapplying/reapplying migrations seems to have fixed things for me- "would be 404s" are no longer causing 500s.  @avelis @digitaldavenyc Thank you!

**Comment by digitaldavenyc** [comment]
@reidransom happy to assist

**Comment by digitaldavenyc** [comment]
I think this could get closed out.

**Comment by digitaldavenyc** [comment]
@avelis I don't think this was resolved, the error is back. Working with a brand new docker container and database locally and the IntegrityError is showing up on all requests. I forced an update to the master on github just make sure I'm on the latest and rebuilt, the error is persisting.

**Comment by avelis** [comment]
@digitaldavenyc Never fear. The bug that will not die is here. So, as I understand it. It's for every request? Instead of just intermittently?

**Comment by digitaldavenyc** [comment]
@avelis It's on every request

**Comment by avelis** [comment]
@digitaldavenyc The only resolution I can think of is completely overhauling the request/response middleware behavior and only save the request object when I want to save the response object.

**Comment by avelis** [comment]
@digitaldavenyc I have removed the extra if check in: 3bc0545f7041c273b762093caeab9c444c3e1f5d

**Comment by mtford90** [comment]
Lots of stabbing in the dark with this issue. Just an idea but I think an integration test that replicates this would help i.e. spin up a Django app on an affected server and blast it with requests until this error shows its ugly face. Could be included in the travis build. It would at least speed up the back and forth on this?

**Comment by digitaldavenyc** [comment]
@mtford90 I agree, all the guessing is not helping resolve this, however, a heavy load isn't really the cause for this error to appear, at least from my experience. Happened on the first request.

**Comment by reidransom** [comment]
@mtford90 @digitaldavenyc When I was testing last week, the errors went away for a bit after dropping and recreating the database table.  After a day or so, they came back consistently.  While the error is not directly caused by heavy load, a smoke test should still reliably reproduce it.

**Comment by mtford90** [comment]
Aye, when I suggested heavy load it was to ensure reproduction as opposed to implying only heavy load caused it.

I really really wish I could take this myself but not only am I swamped but I haven't written a line of python for around 10 months now... Any volunteers? :smile:

**Comment by slavasav** [comment]
Hi, one more affected here. django19, mysql db.

**Comment by alexanderatallah** [comment]
I got rid of most of the errors by moving SilkyMiddleware to the end of my MIDDLEWARE_CLASSES. The errors appeared on URLs without trailing slashes. I set `APPEND_SLASH` to True, also

But I still get the same error for every static file requested, like `favicon.ico` (which exists) and `robots.txt` (which doesn't).

Please help!

**Comment by avelis** [comment]
@alexanderatallah Could you share which version of Django you are using?

**Comment by alexanderatallah** [comment]
@avelis yes, here are a couple dependencies:
`Django==1.8.2
djangorestframework==3.1.0
django-celery==3.1.17
djrill==2.0
psycopg2==2.5.4
gunicorn==19.1.1`

**Comment by alexanderatallah** [comment]
@avelis actually the most recent update might have fixed it. I had to run `python manage.py silk_clear_request_log` first, though

**Comment by avelis** [comment]
@alexanderatallah Clearing the request log might make sense. It would appear that the collector was storing stale data in the result of a 404. Commit: 4355083f21aec8de8ae99f290a864d749deb3b44 addresses that exact scenario. Let me know if it persist again. This issue has become the ultimate zombie bug for me.

**Comment by avelis** [comment]
@digitaldavenyc @nikicat @slavasav @reidransom @jvlomax Anyone available to see if the latest Commit: 4355083f21aec8de8ae99f290a864d749deb3b44 has resolved this issue for you? It might require running the management command `silk_clear_request_log`.

**Comment by dvinegla** [comment]
@avelis, It works for me.
thank you very much!

**Comment by auvipy** [comment]
hopefully this is resolved in master?

**Comment by auvipy** [comment]
@avelis lets close it for now

**Comment by avelis** [comment]
For closure, any release 0.6.2 or newer should have this issue addressed.

**Comment by tyc85** [comment]
Hi all, 
   Despite this being closed for a while, I am seeing the problem on macOS, python 3.7 (same problem for 3.6 and 3.8 as well). It doesn't even take a loaded requests to emerge, and of course the code somehow catch the exception and move on without throwing, but it flooded the logs and likely means the intended feature/behavior is not going to work. I was wondering what I can help to fix this issue. 


```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/silk/middleware.py", line 139, in process_response
    self._process_response(request, response)
  File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/silk/middleware.py", line 118, in _process_response
    silk_response = ResponseModelFactory(response).construct_response_model()
  File "/usr/local/lib/python3.7/site-packages/silk/model_factory.py", line 319, in construct_response_model
    body=b
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1375, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 472, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "silk_response_request_id_key"
DETAIL:  Key (request_id)=(3edb5734-11ef-4256-a5e8-bcb6afb71e1a) already exists.
```
